config/routes.rb
Rails.application.routes.draw do
  resources :lists

  root to: 'home#index'

  get 'activities' => 'home#index'
  get 'admin'      => 'admin/users#index',       :as => :admin
  get 'login'      => 'authentications#new',     :as => :login
  delete 'logout'  => 'authentications#destroy', :as => :logout
  get 'profile'    => 'users#show',              :as => :profile
  get 'signup'     => 'users#new',               :as => :signup

  get '/home/options',  as: :options
  get '/home/toggle',   as: :toggle
  match '/home/timeline', as: :timeline, via: [:get, :put, :post]
  match '/home/timezone', as: :timezone, via: [:get, :put, :post]
  post '/home/redraw',   as: :redraw

  resource :authentication, except: [:index, :edit]
  resources :comments,       except: [:new, :show]
  resources :emails,         only: [:destroy]
  resources :passwords,      only: [:new, :create, :edit, :update]

  resources :accounts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :inspections, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
      get :autocomplete_account_name
    end
    member do
      get :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put :attach
      match :promote, via: [:patch, :put]
      put :reject
    end
  end

  resources :opportunities, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, id: /\d+/ do
    collection do
      post :filter
      match :auto_complete, via: [:get, :post]
    end
    member do
      put :complete
      put :uncomplete
    end
  end

  resources :users, id: /\d+/, except: [:index, :destroy] do
    member do
      get :avatar
      get :password
      match :upload_avatar, via: [:put, :patch]
      patch :change_password
      post :redraw
    end
    collection do
      match :auto_complete, via: [:get, :post]
      get :opportunities_overview
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        match :auto_complete, via: [:get, :post]
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, except: [:index, :show] do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        match :auto_complete, via: [:get, :post]
        get :options
        get :redraw
        post :sort
        get :subform
      end
    end

    resources :tags, except: [:show] do
      member do
        get :confirm
      end
    end

    resources :fields, as: :custom_fields
    resources :fields, as: :core_fields

    resources :settings, only: :index
    resources :plugins,  only: :index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_current_tab, only: :index

  #----------------------------------------------------------------------------
  def index
    # @activities = get_activities
    # @my_tasks = Task.visible_on_dashboard(current_user).includes(:user, :asset).by_due_at
    # @my_opportunities = Opportunity.visible_on_dashboard(current_user).includes(:account, :user, :tags).by_closes_on.by_amount
    # @my_accounts = Account.visible_on_dashboard(current_user).includes(:user, :tags).by_name
    # respond_with(@activities)
  end

  # GET /home/options                                                      AJAX
  #----------------------------------------------------------------------------
  def options
    unless params[:cancel].true?
      @asset = current_user.pref[:activity_asset] || "all"
      @action = current_user.pref[:activity_event] || "all_events"
      @user = current_user.pref[:activity_user] || "all_users"
      @duration = current_user.pref[:activity_duration] || "two_days"
      @all_users = User.order("first_name, last_name")
    end
  end

  # GET /home/redraw                                                       AJAX
  #----------------------------------------------------------------------------
  def redraw
    current_user.pref[:activity_asset] = params[:asset] if params[:asset]
    current_user.pref[:activity_event] = params[:event] if params[:event]
    current_user.pref[:activity_user] = params[:user] if params[:user]
    current_user.pref[:activity_duration] = params[:duration] if params[:duration]
    @activities = get_activities

    respond_with(@activities) do |format|
      format.js { render :index }
    end
  end

  # GET /home/toggle                                                       AJAX
  #----------------------------------------------------------------------------
  def toggle
    if session[params[:id].to_sym]
      session.delete(params[:id].to_sym)
    else
      session[params[:id].to_sym] = true
    end
    render nothing: true
  end

  # GET /home/timeline                                                     AJAX
  #----------------------------------------------------------------------------
  def timeline
    state = params[:state].to_s
    if %w(Collapsed Expanded).include?(state)
      if (model_type = params[:type].to_s).present?
        if %w(comment email).include?(model_type)
          model = model_type.camelize.constantize
          item = model.find(params[:id])
          item.update_attribute(:state, state)
        end
      else
        comments, emails = params[:id].split("+")
        Comment.where(id: comments.split(',')).update_all(state: state) unless comments.blank?
        Email.where(id: emails.split(',')).update_all(state: state) unless emails.blank?
      end
    end

    render nothing: true
  end

  # GET /home/timezone                                                     AJAX
  #----------------------------------------------------------------------------
  def timezone
    #
    # (new Date()).getTimezoneOffset() in JavaScript returns (UTC - localtime) in
    # minutes, while ActiveSupport::TimeZone expects (localtime - UTC) in seconds.
    #
    if params[:offset]
      session[:timezone_offset] = params[:offset].to_i * -60
      ActiveSupport::TimeZone[session[:timezone_offset]]
    end
    render nothing: true
  end

  private


  #----------------------------------------------------------------------------
  # TODO: this is ugly, ugly code. It's being security patched now but urgently
  # needs refactoring to use user id instead. Permuations based on name or email
  # yield incorrect results.
  def activity_user
    user = current_user.pref[:activity_user]
    if user && user != "all_users"
      user = if user =~ /@/ # email
               User.where(email: user).first
             else # first_name middle_name last_name any_name
               name_query = if user.include?(" ")
                              user.name_permutations.map do |first, last|
                                User.where(first_name: first, last_name: last)
                              end.map(&:to_a).flatten.first
                            else
                              [User.where(first_name: user), User.where(last_name: user)].map(&:to_a).flatten.first
               end
        end
    end
    user.is_a?(User) ? user.id : nil
  end

  #----------------------------------------------------------------------------
  def activity_duration
    duration = current_user.pref[:activity_duration]
    if duration
      words = duration.split("_") # "two_weeks" => 2.weeks
      if %w(one two).include?(words.first) && %w(hour day days week weeks month).include?(words.last)
        %w(zero one two).index(words.first).send(words.last)
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def sort_by_assets
    Version::ASSETS.map do |asset|
      %[{ name: "#{t(asset.singularize)}", on_select: function() { #{redraw(:asset, [asset, t(asset.singularize).downcase], url_for(action: :redraw))} } }]
    end
  end

  #----------------------------------------------------------------------------
  def sort_by_events
    Version::EVENTS.map do |event|
      %[{ name: "#{t(event + '_past_participle')}", on_select: function() { #{redraw(:event, [event, t(event + '_past_participle').downcase], url_for(action: :redraw))} } }]
    end
  end

  #----------------------------------------------------------------------------
  def sort_by_duration
    Version::DURATION.map do |duration|
      %[{ name: "#{t(duration)}", on_select: function() { #{redraw(:duration, [duration, t(duration).downcase], url_for(action: :redraw))} } }]
    end
  end

  #----------------------------------------------------------------------------
  def sort_by_users
    users = [["all_users", t(:option_all_users)]] + @all_users.map do |user|
      escaped = sanitize(user.full_name)
      [escaped, escaped]
    end

    users.map do |key, value|
      %[{ name: "#{value}", on_select: function() { #{redraw(:user, [key, (value == t(:option_all_users) ? value.downcase : value)], url_for(action: :redraw))} } }]
    end
  end

  # Activity title for RSS/ATOM feeds.
  #----------------------------------------------------------------------------
  def activity_title(activity)
    user    = activity.user.try(:full_name) || ''
    action  = t('action_' + activity.event)
    type    = t('subject_' + activity.item_type.downcase)
    subject = if item = activity.item
                if item.respond_to?(:full_name)
                  item.full_name
                elsif item.respond_to?(:name)
                  item.name
                end
    end
    t(:activity_text, user: user, action: action, type: type, subject: subject,
                      default: "#{user} #{action} #{type} #{subject}")
  end

  # Displays 'not showing' message for a given count, entity and limit
  def show_hidden_entities_message(count, entity, limit = 10)
    if count > limit
      hidden_count = count - 10
      entity_string = I18n.t("#{hidden_count == 1 ? entity : entity.pluralize}_small")
      content_tag(:p) do
        t(:not_showing_hidden_entities, entity: entity_string, count: hidden_count)
      end
    end
  end
end

app/views/home/_account.html.haml
- amount = account.opportunities.not_lost.map(&:weighted_amount).sum
%li.highlight[account]
  - if account.category
    .strip{:class => account.category} #{t(account.category)}
  - else
    .strip{:style => "color: gray;"} #{t :other}

  .indent
    = link_to(h(account.name), account)
    &ndash;
    %tt
      = account.location << ", " unless account.location.blank?
      - user_name = account.user.try(:full_name)
      - if user_name
        = t(:added_by, :time_ago => timeago(account.created_at), :user => h(user_name)).html_safe
      - else
        = t(:added_ago, :value => timeago(account.created_at)).html_safe

    - unless current_user.preference[:accounts_index_view] == "accounts_index_brief"
      %dt
        = link_to(account.website, account.website.to_url) << " | " if account.website.present?
        = link_to_email(account.email) << " | " if account.email.present?
        = t(:phone_small) << ": " << (account.toll_free_phone || account.phone) << " | " if account.toll_free_phone? || account.phone?
        = t('pluralize.contact', account.contacts.count) << " | "
        = t('pluralize.opportunity', account.opportunities.count)
      - if account.tags.present?
        %dt
          .tags= tags_for_dashboard(account)
      = hook(:account_bottom, self, :account => account)

app/views/home/_activity.html.haml
- user = link_to(activity.user.full_name, user_path(activity.user)) if activity.user

- subject = if (item = activity.related || activity.item)
  - if item.respond_to?(:full_name)
    - link_to item.full_name, polymorphic_url(item)

  - elsif [Account, Campaign, Contact, Lead, Opportunity].include?(item.class)
    - link_to item.name, polymorphic_url(item)

  - elsif item.respond_to?(:name)
    - content_tag :span, item.name, :style => "color:black;" # Individual tasks have no landing pages where we could link to.

- known_event = t('action_' + activity.event, :default => 0) != 0

- if (user.present? && subject.present?) || !known_event
  %li[activity]
    .tools
      %small
        = l(activity.created_at, :format => :short)
    %tt
      - if known_event
        - action = t('action_' + activity.event)
        - type = t('subject_' + activity.item_type.downcase)
        = link_to avatar_for(activity.user, :size => :thumb), user_path(activity.user)
        = t("activity_text", :user => h(user), :action => h(action), :type => h(type), :subject => h(subject), :default => "#{h user} #{h action} #{h type} #{h subject}").html_safe # locales optionally can change the word order for activities using 'activity_text'
        - if ((item = activity.item).class == Comment) and Setting.comments_visible_on_dashboard
          = t('action_create_comment', :comment => truncate(h(item.comment), :length => 90)).html_safe
      - else
        - type = t(activity.item_type.downcase)
        - if item.respond_to? :email
          = avatar_for(item, :size => :thumb)
        = type
        = subject
        = ":"
        = auto_link(t(activity.event))

app/views/home/_assets_menu.html.haml
:plain
  new crm.Menu({
    trigger   : "#asset",
    fade      : 500,
    appear    : 500,
    menu_items: [ #{sort_by_assets.join(",")} ]
  });

app/views/home/_duration_menu.html.haml
:plain
  new crm.Menu({
    trigger   : "#duration",
    fade      : 500,
    appear    : 500,
    width     : 165,
    menu_items: [ #{sort_by_duration.join(",")} ]
  });

app/views/home/_events_menu.html.haml
:plain
  new crm.Menu({
    trigger   : "#event",
    fade      : 500,
    appear    : 500,
    menu_items: [ #{sort_by_events.join(",")} ]
  });

app/views/home/_opportunity.html.haml
%li.highlight[opportunity]
  - if opportunity.stage
    .strip{:class => opportunity.stage}= t(opportunity.stage)
  - else
    .strip.white #{t :other}

  .indent
    = link_to(h(opportunity.name), opportunity)
    - if opportunity.account
      == #{t :from} #{link_to(h(opportunity.account.name), account_path(opportunity.account))}
    %tt
      &ndash;
      - user_name = opportunity.user.try(:full_name)
      - if user_name
        = t(:added_by, :time_ago => timeago(opportunity.created_at), :user => h(user_name)).html_safe
      - else
        = t(:added_ago, :value => timeago(opportunity.created_at)).html_safe
    - unless current_user.preference[:opportunities_index_view] == "opportunities_index_brief"
      %dt
        %b= number_to_currency(opportunity.weighted_amount, :precision => 0) + " | "
        - won_or_lost = %w(won lost).include?(opportunity.stage)
        - unless won_or_lost
          = t(:probability_number, (opportunity.probability || 0).to_s + '%') + " | "
        - if opportunity.closes_on
          - if won_or_lost
            - if opportunity.closes_on >= Date.today
              = t(:closing_date, l(opportunity.closes_on, :format => :mmddyy))
            - else
              = t(:closed_ago_on, :time_ago => distance_of_time_in_words(opportunity.closes_on, Date.today), :date => l(opportunity.closes_on, :format => :mmddyy))
          - elsif opportunity.closes_on > Date.today
            = t(:expected_to_close,  :time => distance_of_time_in_words(Date.today, opportunity.closes_on), :date => l(opportunity.closes_on, :format => :mmddyy))
          - elsif opportunity.closes_on == Date.today
            %span.warn= t(:closes_today)
          - else
            %span.warn= t(:past_due, distance_of_time_in_words(opportunity.closes_on, Date.today))
        - else
          = t(:no_closing_date)
      - if opportunity.tags.present?
        %dt
          .tags= tags_for_dashboard(opportunity)
      = hook(:opportunity_bottom, self, :opportunity => opportunity)

app/views/home/_options.html.haml
%p
  = link_to_close url_for(:action => "options")
  = hidden_field_tag "account[user_id]", current_user.id

  -# activity_options: Show %{models} %{action_type} performed by %{user} in the past %{period}
  = t(:activity_options, :models => link_to(t(h(@asset)).singularize.downcase, "#", :id => :asset), :action_type => link_to(t(h(@action) + "_past_participle").downcase, "#", :id => :event), :user => link_to(t(h(@user)), "#", :id => :user), :period => link_to(t(h(@duration)).downcase, "#", :id => :duration)).html_safe

%script
  = render "assets_menu"
  = render "events_menu"
  = render "users_menu"
  = render "duration_menu"

app/views/home/_task.html.haml
%li.highlight[task]
  - unless task.category.blank?
    .strip{:class => task.category}= t(task.category)
  - else
    .strip.white #{t :other}
  .indent
    %label{ :id => dom_id(task, :name) }
      - if task.user.id != current_user.id
        = t(:task_from, link_to(h(task.user.full_name), user_path(task.user))).html_safe << ':'
      = link_to(task.name, tasks_path)
      - if task.asset_id?
        == #{t :related} #{link_to(task.asset.name, polymorphic_url(task.asset))}
      &ndash;
    %tt
      - if task.bucket == "due_asap"
        %span.urgent= t(:task_due_now)

      - elsif task.bucket == "due_later"
        = t(:task_due_later)

      - else
        - if task.due_at.nil?
          = t(:task_due_later)
        - elsif task.at_specific_time?
          - if task.due_at < Time.now
            %span.warn
              = distance_of_time_in_words(task.due_at, Time.now)
              = t(:task_overdue)
              = l(task.due_at.localtime, :format => :mmddhhss)
          - else
            = t(:task_due_in, distance_of_time_in_words(Time.now, task.due_at))
            = '(' << l(task.due_at.localtime, :format => :mmddhhss) << ')'

        - else
          - if task.due_at < Date.today
            %span.warn
              = distance_of_time_in_words(task.due_at, Time.now)
              = t(:task_overdue)
              = l(task.due_at.localtime.to_date, :format => :mmdd)
          - elsif task.due_at > Date.today
            = t(:task_due_in, distance_of_time_in_words(Time.now, task.due_at.localtime.end_of_day))
            = ' (' << l(task.due_at.localtime.to_date, :format => :mmdd) << ')'
          - else
            %span.cool= t(:task_due_today)

    - unless task.background_info.blank?
      %div
        %dt= auto_link(simple_format task.background_info)

app/views/home/_users_menu.html.haml
:plain
  new crm.Menu({
    trigger   : "#user",
    fade      : 500,
    appear    : 500,
    width     : 180,
    menu_items: [ #{sort_by_users.join(',')} ]
  });

app/views/home/index.html.haml
= styles_for :task, :opportunity, :account

.title
  %span#title #{t :inspections}
%ul.list#inspections
  -#- unless @my_tasks.empty?
  -#  = render :partial => "home/task", :collection => @my_tasks.limit(10)
  -#  = show_hidden_entities_message(@my_tasks.count, 'task', 10)
  -#- else
  #{t :no_inspection_records}

.title
  %span#title #{t :recent_activity}
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")
.remote#options{ hidden }

%ul.list#activities
  -#- unless @activities.empty?
  -#  = render :partial => "activity", :collection => @activities
  -#- else
  #{t :no_activity_records}

app/views/home/index.js.haml
- unless @activities.blank?
  $('#activities').html('#{ j render(:partial => "activity", :collection => @activities) }');
- else
  $('#activities').html('#{ j t(:no_activity_records) }');

-# $('#paginate').html('#{ j render(:partial => "shared/paginate") }');
$('#export').html('#{ j render(:partial => "shared/export") }');

app/views/home/options.js.haml
crm.flip_form('options');

- unless params[:cancel].true?
  $('#options').html('#{ j render(:partial => "options") }');
  crm.set_title('title', '#{ j t(:recent_activity_options) }');
- else
  crm.set_title('title', '#{ j t(:recent_activity) }');