config/routes.rb
Rails.application.routes.draw do
  resources :lists

  root to: 'home#index'

  get 'activities' => 'home#index'
  get 'admin'      => 'admin/users#index',       :as => :admin
  get 'login'      => 'authentications#new',     :as => :login
  delete 'logout'  => 'authentications#destroy', :as => :logout
  get 'profile'    => 'users#show',              :as => :profile
  get 'signup'     => 'users#new',               :as => :signup

  get '/home/options',  as: :options
  get '/home/toggle',   as: :toggle
  match '/home/timeline', as: :timeline, via: [:get, :put, :post]
  match '/home/timezone', as: :timezone, via: [:get, :put, :post]
  post '/home/redraw',   as: :redraw

  resource :authentication, except: [:index, :edit]
  resources :comments,       except: [:new, :show]
  resources :emails,         only: [:destroy]
  resources :passwords,      only: [:new, :create, :edit, :update]

  resources :accounts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :inspections, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
      get :autocomplete_account_name
    end
    member do
      get :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put :attach
      match :promote, via: [:patch, :put]
      put :reject
    end
  end

  resources :opportunities, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, id: /\d+/ do
    collection do
      post :filter
      match :auto_complete, via: [:get, :post]
    end
    member do
      put :complete
      put :uncomplete
    end
  end

  resources :users, id: /\d+/, except: [:index, :destroy] do
    member do
      get :avatar
      get :password
      match :upload_avatar, via: [:put, :patch]
      patch :change_password
      post :redraw
    end
    collection do
      match :auto_complete, via: [:get, :post]
      get :opportunities_overview
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        match :auto_complete, via: [:get, :post]
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, except: [:index, :show] do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        match :auto_complete, via: [:get, :post]
        get :options
        get :redraw
        post :sort
        get :subform
      end
    end

    resources :tags, except: [:show] do
      member do
        get :confirm
      end
    end

    resources :fields, as: :custom_fields
    resources :fields, as: :core_fields

    resources :settings, only: :index
    resources :plugins,  only: :index
  end
end

app/views/layouts/500.html.haml
- content_for(:tabless) do
  500 error

!!!5
%html{ :xmlns => "http://www.w3.org/1999/xhtml", "xml:lang" => :en,  :lang => :en }
  %head
    %meta{ "http-equiv" => "Content-Type", :content => "text/html; charset=utf-8" }
    %title Fat Free CRM Exception
    = stylesheet_link_tag :application
    = javascript_include_tag :application

  %body
    #header
      #welcome
      %h3= link_to("Fat Free CRM", '/')
    %center
      %p.flash_exception#msg= exception

app/views/layouts/_about.html.haml
#about{ hidden }
  %h3
    #{t :about_ffc_version}
    %span.cool== v#{StatiaGov::VERSION::STRING}
    == (#{ActiveRecord::Base.connection.adapter_name.downcase})
  %p
    #{t :about_thank_you}

  #{t :about_ffc_resources}:
  %ul{:style => "margin: 0px 0px 0px 15px"}
    %li== &raquo; #{link_to t(:about_home_page), "http://www.fatfreecrm.com", :"data-popup" => true}
    %li== &raquo; #{link_to t(:about_project_page), "http://github.com/fatfreecrm/statia_gov/tree/master", :"data-popup" => true}
    %li== &raquo; #{link_to t(:about_features), "http://github.com/fatfreecrm/statia_gov/issues", :"data-popup" => true}
    %li== &raquo; #{link_to t(:about_twitter), "http://twitter.com/fatfreecrm", :"data-popup" => true}
    %li== &raquo; #{link_to t(:about_user_group), "http://groups.google.com/group/fat-free-crm-users", :"data-popup" => true}
    %li== &raquo; #{link_to t(:about_dev_group), "http://groups.google.com/group/fat-free-crm-dev", :"data-popup" => true}
  %br

app/views/layouts/_footer.html.haml
#footer

app/views/layouts/_header.html.haml
#header
  #welcome
    #{t :welcome},
    -# This span gets updated on the fly if user changes her name.
    %span#welcome_username= 'Some User'
    %span> !&nbsp;&nbsp;
    = link_to(t(:quick_find), "#", :id => "jumper") << " |"
    = link_to(t(:logout), logout_path, :method => :delete)
    = render "/layouts/jumpbox"
    -#- else
    -#  = link_to(t(:login), login_path) << " |"
    -#  = link_to(t(:sign_up), signup_path) << " |" if can_signup?
    -#  = link_to(t(:about), "#", :title => t(:about_ffc), :onclick => "$('#about').dialog({ title: this.title, modal: true }); return false;")
  %h3
    = link_to("G.G.D Management Application", root_path)

app/views/layouts/_jumpbox.html.haml
- current_auto_complete = session[:auto_complete] || :inspections
= content_for(:javascript_epilogue) do
  :plain
    (function ($) {
      $(function() {
        new crm.Popup({
          trigger     : "#jumper",
          target      : "#jumpbox",
          under       : "#welcome",
          appear      : 300,
          fade        : 300,
          before_show : function() {
            $("#jumper").addClass("selected");
            $("#jumpbox_label").html("");
            $("#jumpbox_label").hide();
            $("#jumpbox_menu").show();
            crm.auto_complete("#{current_auto_complete}");
          },
          after_show  : function() {
            $("#auto_complete_query").focus();
          },
          after_hide  : function() {
            $("#jumper").removeClass("selected");
          }
        });
      });
  })($);

#jumpbox{ hidden }
  %span#jumpbox_menu= jumpbox(current_auto_complete)
  %span#jumpbox_label{ hidden }
  %br
  = text_field_tag "auto_complete_query", nil, :style => "width: 310px", :autocomplete => :off
  .auto_complete#auto_complete_dropdown

app/views/layouts/_sidebar.html.haml
- view   ||= controller.controller_name
- action ||= controller.action_name
- sidebar = "#{view}/sidebar_#{action}"
- sidebar = "admin/#{sidebar}" if controller.class.to_s.starts_with?("Admin::")

= content_for :sidebar
- begin
  = render sidebar
  - rescue MissingTemplate

= render "shared/recently"

app/views/layouts/_tabbed.html.haml
.tabs
  %ul
    - tabs.each do |tab|
      %li
        = link_to(tab[:url], :class => tab[:active] ? "active" : nil) do
          %i.fa{class: tab[:icon]}
          = t(tab[:text])
= show_flash
%table{ :width => "100%", :height => "100%", :cellpadding => 0, :cellspacing => 0, :class => :tabbed }
  %tr
    %td{ :class => :sidebar, :id => :sidebar, :valign => :top }
      = render "layouts/sidebar"
    %td{ :class => :main, :id => :main, :valign => :top }
      = yield

app/views/layouts/_tabless.html.haml
= show_flash(:sticky => true)
.tabless= yield
= render "layouts/footer"

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %meta{ "http-equiv" => "Content-Type", :content => "text/html; charset=utf-8" }
    %title G.G.D Management Application
    == <!-- #{controller.controller_name} : #{controller.action_name} -->
    = stylesheet_link_tag :application
    = stylesheet_link_tag :print, :media => 'print'
    = hook(:stylesheet_includes, self) do
      #{yield :stylesheet_includes}
    %style= yield :styles

    = javascript_include_tag :application

    - unless tabless_layout? || %w(en-US en-GB).include?(I18n.locale.to_s)
      = javascript_include_tag "jquery_ui_datepicker/jquery.ui.datepicker-#{I18n.locale}"
      = javascript_include_tag "jquery_ui_datepicker/jquery-ui-timepicker-#{I18n.locale}"

    = csrf_meta_tag
    = hook(:javascript_includes, self)

    :javascript
      crm.language = "#{I18n.locale}"
      window.controller = "#{controller.controller_name}"

    -#- if current_user.present?
    -#  :javascript
    -#    #{yield :javascript}
    -#    var _ffcrm_users = [
    -#    #{User.all.map{|u| "\"#{j u.full_name} (@#{j u.username})\"" }.join(",\n")}
    -#    ];

    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">

  %body
    = render "layouts/header"
    - if tabless_layout?
      = render "layouts/tabless"
    - else
      = render "layouts/tabbed"
      = render "layouts/footer"

    %script{:type => "text/javascript"}
      = "crm.base_url = '#{Setting.base_url}';" unless Setting.base_url.blank?
      = get_browser_timezone_offset
      = content_for :javascript_epilogue
      = hook(:javascript_epilogue, self)